[build]
  publish = "public"
  command = "gatsby build"
  
  
[build.environment]
  NODE_VERSION = "14"

[[plugins]]
package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "/deconstructed-photography"
  to = "/experiences"
  status = 301